# Generated by Django 3.2.19 on 2023-05-03 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_taskmodel_modificado_em'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskmodel',
            options={'ordering': ('mes_atividade', '-dia_atividade'), 'verbose_name': 'Atividade', 'verbose_name_plural': 'Atividades'},
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='dia_atividade',
            field=models.DateField(verbose_name='Dia'),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='mes_atividade',
            field=models.DateField(verbose_name='Mês'),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='modificado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificado em'),
        ),
    ]
