# Generated by Django 3.2.19 on 2023-05-03 23:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230503_2038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskmodel',
            options={'verbose_name': 'Atividade', 'verbose_name_plural': 'Atividades'},
        ),
        migrations.RemoveField(
            model_name='taskmodel',
            name='dia_atividade',
        ),
        migrations.RemoveField(
            model_name='taskmodel',
            name='mes_atividade',
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='data_atividade',
            field=models.DateField(default=datetime.date(2023, 5, 3), verbose_name='Data da Atividade'),
            preserve_default=False,
        ),
    ]
